In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
csv = pd.read_excel('Desktop/due.xlsx')
csv

     Anno               Comuni        Struttura  Posti letto
0    2008       Albano Laziale      alberghieri          374
1    2008                Anzio      alberghieri         1244
2    2008                Ardea      alberghieri          331
3    2008              Ariccia      alberghieri          206
4    2008      Castel Gandolfo      alberghieri          232
5    2008             Ciampino      alberghieri          284
6    2008              Colonna      alberghieri            0
7    2008             Frascati      alberghieri          899
8    2008      Genzano di Roma      alberghieri          234
9    2008        Grottaferrata      alberghieri          443
10   2008              Lanuvio      alberghieri            0
11   2008               Marino      alberghieri          441
12   2008  Monte Porzio Catone      alberghieri          310
13   2008        Montecompatri      alberghieri          163
14   2008                 Nemi      alberghieri          146
15   2008              Nettuno      alberghieri          469
16   2008              Pomezia      alberghieri         2367
17   2008        Rocca di Papa      alberghieri          260
18   2008         Rocca Priora      alberghieri           78
19   2008             Velletri      alberghieri          210
20   2008       Albano Laziale  extralberghieri          138
21   2008                Anzio  extralberghieri         7455
22   2008                Ardea  extralberghieri         6299
23   2008              Ariccia  extralberghieri          161
24   2008      Castel Gandolfo  extralberghieri           59
25   2008             Ciampino  extralberghieri          607
26   2008              Colonna  extralberghieri            0
27   2008             Frascati  extralberghieri          539
28   2008      Genzano di Roma  extralberghieri          110
29   2008        Grottaferrata  extralberghieri          170
..    ...                  ...              ...          ...
90   2007              Lanuvio      alberghieri            0
91   2007               Marino      alberghieri          381
92   2007  Monte Porzio Catone      alberghieri          310
93   2007        Montecompatri      alberghieri          163
94   2007                 Nemi      alberghieri          146
95   2007              Nettuno      alberghieri          469
96   2007              Pomezia      alberghieri         2181
97   2007        Rocca di Papa      alberghieri          260
98   2007         Rocca Priora      alberghieri           78
99   2007             Velletri      alberghieri          210
100  2007       Albano Laziale  extralberghieri          138
101  2007                Anzio  extralberghieri         7455
102  2007                Ardea  extralberghieri         6303
103  2007              Ariccia  extralberghieri           91
104  2007      Castel Gandolfo  extralberghieri           34
105  2007             Ciampino  extralberghieri          589
106  2007              Colonna  extralberghieri            0
107  2007             Frascati  extralberghieri          534
108  2007      Genzano di Roma  extralberghieri          110
109  2007        Grottaferrata  extralberghieri          167
110  2007              Lanuvio  extralberghieri           47
111  2007               Marino  extralberghieri           78
112  2007  Monte Porzio Catone  extralberghieri           54
113  2007        Montecompatri  extralberghieri          210
114  2007                 Nemi  extralberghieri           20
115  2007              Nettuno  extralberghieri         3160
116  2007              Pomezia  extralberghieri         1960
117  2007        Rocca di Papa  extralberghieri          609
118  2007         Rocca Priora  extralberghieri           48
119  2007             Velletri  extralberghieri          279

[120 rows x 4 columns]

In [3]:
csv.head(3)

   Anno          Comuni    Struttura  Posti letto
0  2008  Albano Laziale  alberghieri          374
1  2008           Anzio  alberghieri         1244
2  2008           Ardea  alberghieri          331

In [47]:
csv2007 = csv[ csv['Anno'] == 2007 ] # seleziona solo i posti letto dell'anno 2007
beds2007 = csv2007['Posti letto']
#csv.loc[(csv['Anno'] == 2007)] altro modo per fare la stessa cosa

In [5]:
print (beds2007) # mostrami tutti i posti letto del 2007

80      374
81     1244
82      322
83      199
84      232
85      258
86        0
87     1130
88      234
89      443
90        0
91      381
92      310
93      163
94      146
95      469
96     2181
97      260
98       78
99      210
100     138
101    7455
102    6303
103      91
104      34
105     589
106       0
107     534
108     110
109     167
110      47
111      78
112      54
113     210
114      20
115    3160
116    1960
117     609
118      48
119     279
Name: Posti letto, dtype: int64

In [7]:
beds2007.head(3) # mostrami solo i primi tre risultati

80     374
81    1244
82     322
Name: Posti letto, dtype: int64

In [8]:
beds2007.describe()

count      40.000000
mean      763.000000
std      1568.235968
min         0.000000
25%        87.750000
50%       233.000000
75%       485.250000
max      7455.000000
Name: Posti letto, dtype: float64

In [9]:
csvstrutt = csv[ csv['Comuni'] == 'Albano Laziale'] #prendimi tutti i posti letto disponibili di albano laziale
albano = csvstrutt['Posti letto']
#csv.loc[(csv['Comuni'] == 'Albano Laziale')] altro modo per fare la stessa cosa

In [10]:
print (albano)

0      374
20     138
40     374
60     136
80     374
100    138
Name: Posti letto, dtype: int64

In [11]:
albano_laziale = csv[ csv['Comuni'] == 'Albano Laziale'] #prendimi tutti i posti letto disponibili di albano laziale nel 2007
anno2007= albano_laziale[albano_laziale['Anno'] == 2007]
bedsalbano2007 = anno2007['Posti letto']

In [12]:
print (bedsalbano2007)

80     374
100    138
Name: Posti letto, dtype: int64

In [13]:
csv.loc[(csv['Comuni'] == 'Albano Laziale') & (csv['Anno'] == 2007)] # altro modo per effettuare condizione di cui sopra

     Anno          Comuni        Struttura  Posti letto
80   2007  Albano Laziale      alberghieri          374
100  2007  Albano Laziale  extralberghieri          138

In [14]:
csv.columns # elenca il nome delle colonne

Index(['Anno', 'Comuni', 'Struttura', 'Posti letto'], dtype='object')

In [15]:
csv.shape # per mostrarti quante righe e colonne sono disponibili (120 righe x 4 colonne)

(120, 4)

In [16]:
csv['Posti letto'].min(), csv['Posti letto'].max() # mostrami il minimo e il massimo di posti letto disponibili

(0, 7470)

In [18]:
csv.groupby('Posti letto') # raggruppami il dataframe per posti letto

In [19]:
posti_mean = csv.groupby('Posti letto').min() # raggruppami i posti letto in ordine crescente

In [21]:
posti_mean.head(10)

             Anno               Comuni        Struttura
Posti letto
0            2006              Colonna      alberghiera
20           2006                 Nemi  extralberghiera
25           2006      Castel Gandolfo  extralberghiera
34           2007      Castel Gandolfo  extralberghieri
43           2006              Lanuvio  extralberghiera
45           2008         Rocca Priora  extralberghieri
47           2007              Lanuvio  extralberghieri
48           2007         Rocca Priora  extralberghieri
49           2006         Rocca Priora  extralberghiera
54           2006  Monte Porzio Catone  extralberghiera

In [23]:
posti100_200 = posti_mean.loc[100:200, :] # raggruppami i posti letto in ordine crescente da 100 a 200
posti100_200

             Anno               Comuni        Struttura
Posti letto
100          2006              Ariccia  extralberghiera
104          2006      Genzano di Roma  extralberghiera
110          2007      Genzano di Roma  extralberghieri
127          2006        Grottaferrata  extralberghiera
136          2006       Albano Laziale  extralberghiera
138          2007       Albano Laziale  extralberghieri
146          2006                 Nemi      alberghiera
157          2006  Monte Porzio Catone      alberghiera
161          2008              Ariccia  extralberghieri
163          2007        Montecompatri      alberghieri
164          2006        Montecompatri      alberghiera
167          2007        Grottaferrata  extralberghieri
170          2008        Grottaferrata  extralberghieri
199          2006              Ariccia      alberghiera

In [24]:
csv['Posti letto']

0       374
1      1244
2       331
3       206
4       232
5       284
6         0
7       899
8       234
9       443
10        0
11      441
12      310
13      163
14      146
15      469
16     2367
17      260
18       78
19      210
20      138
21     7455
22     6299
23      161
24       59
25      607
26        0
27      539
28      110
29      170
       ...
90        0
91      381
92      310
93      163
94      146
95      469
96     2181
97      260
98       78
99      210
100     138
101    7455
102    6303
103      91
104      34
105     589
106       0
107     534
108     110
109     167
110      47
111      78
112      54
113     210
114      20
115    3160
116    1960
117     609
118      48
119     279
Name: Posti letto, Length: 120, dtype: int64

In [27]:
posti0_100 = posti_mean.loc[0:100, :] # raggruppami i posti letto in ordine crescente da 0 a 100
posti0_100

             Anno               Comuni        Struttura
Posti letto
0            2006              Colonna      alberghiera
20           2006                 Nemi  extralberghiera
25           2006      Castel Gandolfo  extralberghiera
34           2007      Castel Gandolfo  extralberghieri
43           2006              Lanuvio  extralberghiera
45           2008         Rocca Priora  extralberghieri
47           2007              Lanuvio  extralberghieri
48           2007         Rocca Priora  extralberghieri
49           2006         Rocca Priora  extralberghiera
54           2006  Monte Porzio Catone  extralberghiera
59           2008      Castel Gandolfo  extralberghieri
77           2006               Marino  extralberghiera
78           2006               Marino      alberghiera
84           2008               Marino  extralberghieri
91           2007              Ariccia  extralberghieri
100          2006              Ariccia  extralberghiera

In [29]:
ariccia = csv[csv['Comuni'] == 'Ariccia'] # selezionami solo il dataframe ariccia
ariccia
#csv.loc[(csv['Comuni'] == 'Ariccia')] altro modo per fare l'operazione di cui sopra

     Anno   Comuni        Struttura  Posti letto
3    2008  Ariccia      alberghieri          206
23   2008  Ariccia  extralberghieri          161
43   2006  Ariccia      alberghiera          199
63   2006  Ariccia  extralberghiera          100
83   2007  Ariccia      alberghieri          199
103  2007  Ariccia  extralberghieri           91

In [34]:
asi = csv.loc[:, 'Comuni'] # selezionami solo i comuni
asi.head(3)

0    Albano Laziale
1             Anzio
2             Ardea
Name: Comuni, dtype: object

In [35]:
csv['Accumulo'] = csv['Anno'].apply(lambda year: 2018 - year) # aggiungo la colonna accumulo che mi indica prendendo come riferimento l'anno quanti anni sono passati 
csv.head(10)

   Anno           Comuni    Struttura  Posti letto  Accumulo
0  2008   Albano Laziale  alberghieri          374        10
1  2008            Anzio  alberghieri         1244        10
2  2008            Ardea  alberghieri          331        10
3  2008          Ariccia  alberghieri          206        10
4  2008  Castel Gandolfo  alberghieri          232        10
5  2008         Ciampino  alberghieri          284        10
6  2008          Colonna  alberghieri            0        10
7  2008         Frascati  alberghieri          899        10
8  2008  Genzano di Roma  alberghieri          234        10
9  2008    Grottaferrata  alberghieri          443        10

In [37]:
csv.sort_values('Posti letto') #riordino il csv in ordine crescente sulla base dei posti letto
csv.head(10)

   Anno           Comuni    Struttura  Posti letto  Accumulo
0  2008   Albano Laziale  alberghieri          374        10
1  2008            Anzio  alberghieri         1244        10
2  2008            Ardea  alberghieri          331        10
3  2008          Ariccia  alberghieri          206        10
4  2008  Castel Gandolfo  alberghieri          232        10
5  2008         Ciampino  alberghieri          284        10
6  2008          Colonna  alberghieri            0        10
7  2008         Frascati  alberghieri          899        10
8  2008  Genzano di Roma  alberghieri          234        10
9  2008    Grottaferrata  alberghieri          443        10

In [39]:
csv.sort_values('Comuni') #riordino il csv in ordine crescente(ordine alfabetico) sulla base dei comuni
csv.head(10)

   Anno           Comuni    Struttura  Posti letto  Accumulo
0  2008   Albano Laziale  alberghieri          374        10
1  2008            Anzio  alberghieri         1244        10
2  2008            Ardea  alberghieri          331        10
3  2008          Ariccia  alberghieri          206        10
4  2008  Castel Gandolfo  alberghieri          232        10
5  2008         Ciampino  alberghieri          284        10
6  2008          Colonna  alberghieri            0        10
7  2008         Frascati  alberghieri          899        10
8  2008  Genzano di Roma  alberghieri          234        10
9  2008    Grottaferrata  alberghieri          443        10

In [40]:
csv.loc[(csv['Anno'] == 2007)]

     Anno               Comuni        Struttura  Posti letto  Accumulo
80   2007       Albano Laziale      alberghieri          374        11
81   2007                Anzio      alberghieri         1244        11
82   2007                Ardea      alberghieri          322        11
83   2007              Ariccia      alberghieri          199        11
84   2007      Castel Gandolfo      alberghieri          232        11
85   2007             Ciampino      alberghieri          258        11
86   2007              Colonna      alberghieri            0        11
87   2007             Frascati      alberghieri         1130        11
88   2007      Genzano di Roma      alberghieri          234        11
89   2007        Grottaferrata      alberghieri          443        11
90   2007              Lanuvio      alberghieri            0        11
91   2007               Marino      alberghieri          381        11
92   2007  Monte Porzio Catone      alberghieri          310        11
93   2007        Montecompatri      alberghieri          163        11
94   2007                 Nemi      alberghieri          146        11
95   2007              Nettuno      alberghieri          469        11
96   2007              Pomezia      alberghieri         2181        11
97   2007        Rocca di Papa      alberghieri          260        11
98   2007         Rocca Priora      alberghieri           78        11
99   2007             Velletri      alberghieri          210        11
100  2007       Albano Laziale  extralberghieri          138        11
101  2007                Anzio  extralberghieri         7455        11
102  2007                Ardea  extralberghieri         6303        11
103  2007              Ariccia  extralberghieri           91        11
104  2007      Castel Gandolfo  extralberghieri           34        11
105  2007             Ciampino  extralberghieri          589        11
106  2007              Colonna  extralberghieri            0        11
107  2007             Frascati  extralberghieri          534        11
108  2007      Genzano di Roma  extralberghieri          110        11
109  2007        Grottaferrata  extralberghieri          167        11
110  2007              Lanuvio  extralberghieri           47        11
111  2007               Marino  extralberghieri           78        11
112  2007  Monte Porzio Catone  extralberghieri           54        11
113  2007        Montecompatri  extralberghieri          210        11
114  2007                 Nemi  extralberghieri           20        11
115  2007              Nettuno  extralberghieri         3160        11
116  2007              Pomezia  extralberghieri         1960        11
117  2007        Rocca di Papa  extralberghieri          609        11
118  2007         Rocca Priora  extralberghieri           48        11
119  2007             Velletri  extralberghieri          279        11

In [42]:
group_posti = csv.groupby('Posti letto').min()
group_posti

             Anno               Comuni        Struttura  Accumulo
Posti letto
0            2006              Colonna      alberghiera        10
20           2006                 Nemi  extralberghiera        10
25           2006      Castel Gandolfo  extralberghiera        12
34           2007      Castel Gandolfo  extralberghieri        11
43           2006              Lanuvio  extralberghiera        12
45           2008         Rocca Priora  extralberghieri        10
47           2007              Lanuvio  extralberghieri        10
48           2007         Rocca Priora  extralberghieri        11
49           2006         Rocca Priora  extralberghiera        12
54           2006  Monte Porzio Catone  extralberghiera        10
59           2008      Castel Gandolfo  extralberghieri        10
77           2006               Marino  extralberghiera        12
78           2006               Marino      alberghiera        10
84           2008               Marino  extralberghieri        10
91           2007              Ariccia  extralberghieri        11
100          2006              Ariccia  extralberghiera        12
104          2006      Genzano di Roma  extralberghiera        12
110          2007      Genzano di Roma  extralberghieri        10
127          2006        Grottaferrata  extralberghiera        12
136          2006       Albano Laziale  extralberghiera        12
138          2007       Albano Laziale  extralberghieri        10
146          2006                 Nemi      alberghiera        10
157          2006  Monte Porzio Catone      alberghiera        12
161          2008              Ariccia  extralberghieri        10
163          2007        Montecompatri      alberghieri        10
164          2006        Montecompatri      alberghiera        12
167          2007        Grottaferrata  extralberghieri        11
170          2008        Grottaferrata  extralberghieri        10
199          2006              Ariccia      alberghiera        11
206          2008              Ariccia      alberghieri        10
...           ...                  ...              ...       ...
421          2006              Nettuno      alberghiera        12
441          2008               Marino      alberghieri        10
443          2007        Grottaferrata      alberghieri        10
448          2006        Grottaferrata      alberghiera        12
469          2007              Nettuno      alberghieri        10
474          2006             Frascati  extralberghiera        12
534          2007             Frascati  extralberghieri        11
539          2008             Frascati  extralberghieri        10
543          2006        Rocca di Papa  extralberghiera        12
555          2006             Ciampino  extralberghiera        12
589          2007             Ciampino  extralberghieri        11
607          2008             Ciampino  extralberghieri        10
609          2007        Rocca di Papa  extralberghieri        11
612          2008        Rocca di Papa  extralberghieri        10
756          2008              Pomezia  extralberghieri        10
899          2008             Frascati      alberghieri        10
907          2006             Frascati      alberghiera        12
1130         2007             Frascati      alberghieri        11
1242         2006                Anzio      alberghiera        12
1244         2007                Anzio      alberghieri        10
1346         2006              Pomezia  extralberghiera        12
1960         2006              Nettuno  extralberghiera        11
2181         2006              Pomezia      alberghiera        11
2367         2008              Pomezia      alberghieri        10
3160         2007              Nettuno  extralberghieri        10
6297         2006                Ardea  extralberghiera        12
6299         2008                Ardea  extralberghieri        10
6303         2007                Ardea  extralberghieri        11
7455         2007                Anzio  extralberghieri        10
7470         2006                Anzio  extralberghiera        12

[80 rows x 4 columns]

In [51]:
csv.loc[(csv['Comuni'] == 'Anzio') & (csv['Anno'] == 2007) & (csv['Struttura'] == 'alberghieri') & (csv['Posti letto'] > 1000)]

    Anno Comuni    Struttura  Posti letto  Accumulo
81  2007  Anzio  alberghieri         1244        11